API_CONNECTION: #Параметры подключения к API сайта с информацией о валютах
  URL: http://api.exchangeratesapi.io/v1
  Token: 767c2ca2b7941cb74f56f0ffe615db7a
  Currency:
      - USD
      - EUR
      - RUB
      - CNY
  Base: EUR
DATABASE:
  Host: localhost
  UserName: admin
  Password: test12345
  Port: 3306
  Databases:
    WareHouse: dwh

